### ISSUE TITLE
livereload doesn't work in firefox/linux

### ISSUE THREAD

**Issue by ralyodio** [primatejs/primate#52]
````
node:internal/errors:497
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_STATE]: Invalid state: Controller is already closed
    at new NodeError (node:internal/errors:406:5)
    at ReadableStreamDefaultController.enqueue (node:internal/webstreams/readablestream:1065:13)
    at file:///home/ettinger/src/hynt.us/hynt-web/node_modules/@primate/build/src/builders/esbuild/module.js:44:12
    at Array.forEach (<anonymous>)
    at inform (file:///home/ettinger/src/hynt.us/hynt-web/node_modules/@primate/build/src/builders/esbuild/module.js:43:11)
    at FSWatcher.<anonymous> (file:///home/ettinger/src/hynt.us/hynt-web/node_modules/@primate/build/src/builders/esbuild/module.js:141:13) {
  code: 'ERR_INVALID_STATE'
}

Node.js v20.9.0
````

**Comment by ralyodio** [comment]
it appears to happen when my firefox browser isn't in focus.

**Comment by ralyodio** [comment]
https://github.com/evanw/esbuild/issues/3507
