### ISSUE TITLE
Can't use primate in windows

### ISSUE THREAD

**Issue by safwanolaimat** [primatejs/primate#76]
Error:
```
node:internal/process/esm_loader:40
      internalBinding('errors').triggerUncaughtException(
                                ^

[Error: ENOENT: no such file or directory, open 'C:\C:\Users\...\AppData\Local\pnpm\store\v3\tmp\dlx-27636\node_modules\.pnpm\create-primate@0.10.0\node_modules\create-primate\package.json'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\C:\\Users\\...\\AppData\\Local\\pnpm\\store\\v3\\tmp\\dlx-27636\\node_modules\\.pnpm\\create-primate@0.10.0\\node_modules\\create-primate\\package.json'
}
```

Reproduce steps:
`pnpm create primate`

**Comment by terrablue** [comment]
Hi, could you please try again? `pnpm create primate@latest`

**Comment by safwanolaimat** [comment]
@terrablue 
```
!! primate error in config file: Only URLs with a scheme in: file, data, and node are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
++ check errors in config file by running node C:\Users\uuu\workspace\primate-test\primate.config.js
   -> https://primatejs.com/modules/primate#error-in-config-file
~~ bye
```

**Comment by terrablue** [comment]
Creating and running a Primate app on Windows should work as of the latest `create-primate` ([f3470e5](https://github.com/primatejs/primate/commit/f3470e5e23c53b1a24575bfb9b8ae436b52ea515)), could you please try again and confirm?

**Comment by safwanolaimat** [comment]
@terrablue 
Now its working

Thanks

**Comment by safwanolaimat** [comment]
@terrablue 


```
PS C:\Users\xxx\workspace\primate-test> npx primate
primate 0.29.5 at http://localhost:6161
X [ERROR] Could not resolve "./components/C:Usersxxxworkspaceprimate-testcomponents\test.svelte.js"

    <stdin>:4:45:
      4 │ ...svelte_8f2f23971c8e} from "./components/C:\Users\xxx\workspace\primate-test\components\test.svelte.js";
        ╵                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

C:\Users\xxx\workspace\primate-test\node_modules\.pnpm\esbuild@0.20.0\node_modules\esbuild\lib\main.js:1651
  let error = new Error(text);
              ^

Error: Build failed with 1 error:
<stdin>:4:45: ERROR: Could not resolve "./components/C:Usersxxxworkspaceprimate-testcomponents\test.svelte.js"
    at failureErrorWithLog (C:\Users\xxx\workspace\primate-test\node_modules\.pnpm\esbuild@0.20.0\node_modules\esbuild\lib\main.js:1651:15)
    at C:\Users\xxx\workspace\primate-test\node_modules\.pnpm\esbuild@0.20.0\node_modules\esbuild\lib\main.js:1059:25
    at C:\Users\xxx\workspace\primate-test\node_modules\.pnpm\esbuild@0.20.0\node_modules\esbuild\lib\main.js:1004:52
    at buildResponseToResult (C:\Users\xxx\workspace\primate-test\node_modules\.pnpm\esbuild@0.20.0\node_modules\esbuild\lib\main.js:1057:7)
    at C:\Users\xxx\workspace\primate-test\node_modules\.pnpm\esbuild@0.20.0\node_modules\esbuild\lib\main.js:1069:9
    at new Promise (<anonymous>)
    at requestCallbacks.on-end (C:\Users\xxx\workspace\primate-test\node_modules\.pnpm\esbuild@0.20.0\node_modules\esbuild\lib\main.js:1068:54)
    at handleRequest (C:\Users\xxx\workspace\primate-test\node_modules\.pnpm\esbuild@0.20.0\node_modules\esbuild\lib\main.js:732:17)
    at handleIncomingPacket (C:\Users\xxx\workspace\primate-test\node_modules\.pnpm\esbuild@0.20.0\node_modules\esbuild\lib\main.js:757:7)
    at Socket.readFromStdout (C:\Users\xxx\workspace\primate-test\node_modules\.pnpm\esbuild@0.20.0\node_modules\esbuild\lib\main.js:680:7) {
  errors: [Getter/Setter],
  warnings: [Getter/Setter]
}

Node.js v21.6.1

```

**Comment by safwanolaimat** [comment]
using the bundler causing the above error

**Comment by terrablue** [comment]
Published new versions of several packages. It should now work if you reinstall the packages.

I also tested against https://primatejs.com/primate/app. As far as I can tell, everything now works on Windows, including Wasm routes (ruby/python -- haven't got around to check go yet), data stores as well as frontends.

**Comment by terrablue** [comment]
@safwanolaimat is this working for you?

**Comment by tguelcan** [comment]
With $npm create primate@latest
Same error on MAC 14.6.1 with bun and/ or node runtime.
htmx > store json > seassion > types

**Comment by terrablue** [comment]
@tguelcan hey. I've released a new version of `create-primate`, could you try again (with `npm create primate@latest`.

I tested the path ` htmx > store json > seassion > types`.

In addition, the error pages are now fixed.
